import sys

cdDriveLetter = ""
cdDeviceName = ""
cdInfoExe = ""
prebatchExe = ""
loadExe = ""
unloadExe = ""
rejectExe = ""
isoBusterExe = ""
cueRipperExe = ""
cdParanoiaExe = ""
cdrdaoExe = ""
shnToolExe = ""
tempDir = ""
rootDir= ""
batchFolder = ""
jobsFolder = ""
secondsToTimeout = ""
quitFlag = False
