#! /usr/bin/env python
"""Shared configuration constants"""

version = ""
cdDriveLetter = ""
cdDeviceName = ""
reportFormatString = ""
cdInfoExe = ""
prebatchExe = ""
loadExe = ""
unloadExe = ""
rejectExe = ""
isoBusterExe = ""
dBpowerampConsoleRipExe = ""
shntoolExe = ""
flacExe = ""
tempDir = ""
rootDir = ""
batchFolder = ""
batchManifest = ""
jobsFolder = ""
secondsToTimeout = ""
prefixBatch = ""
audioFormat = ""
jobsFailedFolder = ""
socketHost = ""
socketPort = ""
startOnFinalise = ""
enablePPNLookup = ""
enableSocketAPI = ""
quitFlag = False
batchIsOpen = False
readyToStart = False
finishedBatch = False
